### ISSUE TITLE
Pantalla Editar

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#1]
No se están mostrando los datos asociados al animal. Debemos mostrarlos para ser editables.

**Comment by JuanmaG** [comment]
La informacion deberia aparecer desde este commit https://github.com/JuanmaG/GQP/commit/130d733d7c5f38303e608122ef52d2d61f9d4c05

**Comment by bukosabino** [comment]
Falta rellenar los selects

**Comment by JuanmaG** [comment]
He intentado poner los valores de los datos del perro en los select como seleccionados por defecto pero no son mostrados como tal hasta que se hace click, estoy intentando encontrar otra solucion. commit:https://github.com/JuanmaG/GQP/commit/ee153de917848a5a7e701fb8edbdd3f6592293cc

**Comment by bukosabino** [comment]
Te he dejado un ejemplo de select que automaticamente selecciona el valor que ya viene seleccionado. Explora todos los cambios realizados en este commit https://github.com/JuanmaG/GQP/commit/12b586b2d4cfe0ef8c93cbcf4b2dc5a6993297c5

**Comment by JuanmaG** [comment]
Selects rellenados TODO listo commit:https://github.com/JuanmaG/GQP/commit/fd698e1306c50995d00514f5266a68cc8a763f91
