### ISSUE TITLE
Pantalla Detalle

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#10]
Los botones "editar" y "borrar" solamente han de aparecer si el anuncio pertenece al usuario que los ha subido.

**Comment by JuanmaG** [comment]
Solo deberia mostrar los botones al propietario del anuncio(trabajando solo con la api nueva, en las pestañas de la vieja no funcionará)
commit:https://github.com/JuanmaG/GQP/commit/9ad38af96d72a93d1f2f0a067ca387075f2eb4a9
