### ISSUE TITLE
Pantalla Detalle

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#2]
Necesitamos mostrar todos los datos asociados a un animal (como la raza, los datos de contacto, etc.). Es necesario pensar de qué manera quedan mejor distribuidos e implementar una propuesta.

**Comment by JuanmaG** [comment]
Sí, precisamente estoy con ello,en la vista detallada he cambiado uno de
los botones para que muestre la información de contacto y localización en
vez de la historia,en un momento pusheo

**Comment by JuanmaG** [comment]
Intento de mejora de la vista,cuando se esta viendo en detalle darle al botón del telefono hace que aparezca la informacion de contacto/la del perro (pensando como hacer esto mas intuitivo) y tambien tocado un poco el browser para que no se vea tan pesado.
https://github.com/JuanmaG/GQP/commit/70da5d695eed7646d953c40752a884ded01d33c1

**Comment by bukosabino** [comment]
Lo ideal sería mostrar directamente toda la información. Sin usar botones que oculten y muestren información

**Comment by JuanmaG** [comment]
Cambiado,no clicks necesarios,toda la informacion desplegada commit:https://github.com/JuanmaG/GQP/commit/ee153de917848a5a7e701fb8edbdd3f6592293cc

**Comment by bukosabino** [comment]
Le he metido algun campo que le faltaba
