### ISSUE TITLE
Pantalla de Listado

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#3]
1 - Mientras se carga el listado de perros viene bien poner un spinner: https://ionicframework.com/docs/api/components/spinner/Spinner/ o un mensaje de "cargando..." : https://ionicframework.com/docs/api/components/loading/LoadingController/

2 - Cuando estamos viendo los primeros perros y desplazamos hacia abajo hacer una recarga de los datos consultándolos a la API:
https://ionicframework.com/docs/api/components/refresher/Refresher/
https://www.youtube.com/watch?v=nN31hsIYYj4

**Comment by bukosabino** [comment]
He añadido un fabbutton para añadir animales.

Aparte he modificado un poco el togglemenu (arriba izquierda). Puedes ir planteando ya la pantalla de "configuración" y la de "listado de mis propios perros subidos".

**Comment by JuanmaG** [comment]
Añadido spinner con loading controller al abrir la aplicacion e ir al browser commit:https://github.com/JuanmaG/GQP/commit/2797abaea86c10d3fac48f78aaf01d8bca459b65

Recarga de datos consultandolos a la api con refresher commit:https://github.com/JuanmaG/GQP/commit/b920d0807f523353ede6a5c87aadec4077552b63

Añadida pagina de configuración commit:https://github.com/JuanmaG/GQP/commit/f04b4d5ec5852a81fc6972bfee6bef035c11dffe

Añadida una etapa muy verde de una idea para la pagina de "mis Anuncios" usando sliders
commit:https://github.com/JuanmaG/GQP/commit/5887713e969284e2e4f788d463776e981e4e6531
