### ISSUE TITLE
Estilo de código

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#5]
Vamos a intentar seguir alguna guía de estilo de código. Por ejemplo esta:

https://angular.io/guide/styleguide

He modificado el estilo del fichero src/pages/vista/vista.ts como ejemplo.

No hay por qué seguirla al dedillo, pero como mínimo llevar la altura de las llaves, sangrías, dejar espacios entre funciones. Así, el código será más leíble.

**Comment by bukosabino** [comment]
Cuando hacemos ionic serve o ionic cordova build el tslint te muestra algunos warnings de paquetes que no usamos. Haría falta limpiarlo.

**Comment by JuanmaG** [comment]
limpiado commit:https://github.com/JuanmaG/GQP/commit/51eba392aa745f64087073a4f6e74193ebd4604e
