### ISSUE TITLE
Pantalla Mis Anuncios

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#6]
- Vigilar la navegabilidad en esta pantalla (Botón Atrás)

- Vigila que en el listado se pueda pulsar un botón para compartir y entrar a la vista de editar. Creo que lo tienes así pensado viendo el código pero ahoramismo no funciona del todo, no?

**Comment by JuanmaG** [comment]
Si eso es lo que he pensado pero hice el esqueleto y no he tocado mas esa pagina le di mas prioridad a arreglar lo del build y estas ultimas cosas,si no hoy mañana le dare a esa pagina.

**Comment by JuanmaG** [comment]
He puesto para que aparezcan todos los perros en mis anuncios provisionalmente,se puede navegar a la pagina de editar,el share aun no funciona en esta pagina commit:https://github.com/JuanmaG/GQP/commit/6ac7a2da37dc766b51fab7b77b87e1a3821529ae

**Comment by bukosabino** [comment]
Añadir botón eliminar

**Comment by JuanmaG** [comment]
Boton eliminar, slide al hacer click commit:https://github.com/JuanmaG/GQP/commit/0abbaf3a69deec874d7ef3777867f36d71d04cfd

**Comment by JuanmaG** [comment]
Solo muestra los anuncios del usuario actual
commit:https://github.com/JuanmaG/GQP/commit/e9212cb49e796f90166bee68b42f665284cfcdd4
