### ISSUE TITLE
Limpieza de plugins

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#8]
Plugins como screenshot y no estoy seguro de si image-picker han dejado de tener utilidad.

**Comment by JuanmaG** [comment]
No me habia dado cuenta pero si image picker no funciona tendre que ver que hay como alternativa

**Comment by bukosabino** [comment]
Perdona, me refería a screenshot nada más. Por aquello de que ya compartimos con el plugin https://ionicframework.com/docs/native/social-sharing/
