### ISSUE TITLE
Ionic tabs

### ISSUE THREAD

**Issue by bukosabino** [JuanmaG/GQP#9]
Para separar perros adoptados, en acogida, perdidos o encontrados.

Te recomiendo usar este: https://github.com/zyra/ionic2-super-tabs

No es exactamente un plugin, sino solamente un paquete typescript instalable con npm.

Si te da problemas dame el toque!

**Comment by JuanmaG** [comment]
He metido los tabs pero por alguna razón no se puede hacer scroll en los browsers nose si sera algún problema de compatibilidad o que no estoy viendo algo commit:https://github.com/JuanmaG/GQP/commit/8135387058a66b5a8330e9ca611d73efac36731b

**Comment by JuanmaG** [comment]
Ya funcionan los tabs pero ahora hay que arreglar la vista detallada porque se ve muy raro commit:https://github.com/JuanmaG/GQP/commit/b8a66c76e7659edbce8f068eaff119422d0df1a0

**Comment by JuanmaG** [comment]
Idea de arreglo de la vista detallada commit:https://github.com/JuanmaG/GQP/commit/8e35a6af8a10706609875e8d6da1b8c80cd7c4f5
